### ISSUE TITLE
Testing locally throws zipkin error 

### ISSUE THREAD

**Issue by luebken** [redhat-helloworld-msa/bonjour#4]
I followed the readme (npm install & npm start) and opened the url http://localhost:8080/api/bonjour

And I get the following error. Not sure how to deal with it

```

npm start

> bonjour@1.0.0 start /Users/mdl/tmp/bonjour
> node bonjour.js

Bonjour service running at http://0.0.0.0:8080
Error sending Zipkin data Error: only absolute urls are supported
    at /Users/mdl/tmp/bonjour/node_modules/node-fetch/index.js:54:10
    at new Fetch (/Users/mdl/tmp/bonjour/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/mdl/tmp/bonjour/node_modules/node-fetch/index.js:37:10)
    at HttpLogger.processQueue (/Users/mdl/tmp/bonjour/node_modules/zipkin-transport-http/src/HttpLogger.js:24:7)
    at Timeout.HttpLogger.setInterval [as _repeat] (/Users/mdl/tmp/bonjour/node_modules/zipkin-transport-http/src/HttpLogger.js:10:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at Timer.unrefdHandle (timers.js:454:14)
```

**Comment by rafabene** [comment]
I think you should ignore that. It expects a running zipkin server (where the URL comes from the ZIPKIN_SERVER_URL environment variable).
